apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: botkube-civo-demo
resources:
- helmrelease-botkube.yaml
- helmrepo-botkube.yaml
- namespace-botkube-civo-demo.yaml
commonLabels:
  botkube-civo: demo
  dev: nebarilabs
patchesStrategicMerge:
- patch-clustername.yaml
- patch-discord.yaml
- patch-flux.yaml
- patch-helm.yaml
- patch-kubectl.yaml
