apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease-botkube.yaml
- helmrepo-botkube.yaml
- patch-clustername.yaml
commonLabels:
  botkube-civo: demo
  dev: nebarilabs
patchesStrategicMerge:
- patch-clustername.yaml

